# Do not edit!  This file was autogenerated
#      by ./cleanup
#      on Fri Jan 15 16:11:37 CET 2010
#
# SVNVERSION as reported by svnversion at that point in time,

SVNVERSION <- "9014"
SVNDATE <- "2010-01-15 15:03:38"

