# Do not edit!  This file was autogenerated
#      by ./cleanup
#      on Fri Jan 15 10:08:28 CET 2010
#
# SVNVERSION as reported by svnversion at that point in time,

SVNVERSION <- "8996"
SVNDATE <- "2010-01-15 09:31:58"

