# Do not edit!  This file was autogenerated
#      by ./cleanup
#      on Fri Jan 22 11:24:22 CET 2010
#
# SVNVERSION as reported by svnversion at that point in time,

SVNVERSION <- "9100"
SVNDATE <- "2010-01-22 11:21:15"

